name: social_share
description: Flutter plugin to share images on social media. Such as sharing on Instagram, Facebook story ,Twitter, Sms and other popular sharing options.
version: 0.0.3
author: Shekar Mudaliyar <sskshekar10@gmail.com>
homepage: https://github.com/ShekarMudaliyar/social_share

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shekarmudaliyar.social_share
    pluginClass: SocialSharePlugin
