name: social_share
description: Wide variety of sharing options you'll need to share directly to certain apps. This plugin includes share to Instagram-story, Facebook-story, Twitter, Sms, Copy to clipboard , and default option to share.
version: 1.0.0
author: Shekar Mudaliyar <sskshekar10@gmail.com>
homepage: https://github.com/ShekarMudaliyar/social_share

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shekarmudaliyar.social_share
    pluginClass: SocialSharePlugin
